### PR TITLE
Updates WordPress Service gitignore to include Composer auth.json

### PR DESCRIPTION
**Pull request by timnolte**
* Changes the Composer COPY for Dockerfile generation to use wildcards in order to properly capture the optional auth.json file which may be needed for WordPress Premium Plugin/Theme installation.

### CODE REVIEW

**Comment by gustavderdrache** [comment]
I'm not too familiar with this file, so I've got a few questions:

1. What is the role of `auth.json`? Is it like a `.env` file in that it may contain sensitive information and thus not be committed?
2. This `COPY` command is acceptable but might be a bit too generous, given that it's possible that other `.json` files may appear in the repository and cause unneeded Docker cache invalidations. Is it safe to use an empty JSON object? If so, should we consider scaffolding an empty one for all projects?

**Comment by timnolte** [comment]
@gustavderdrache sorry I didn't see the notification on this.

1. The `auth.json` is the Composer configuration file that manages authentication for repositories. https://getcomposer.org/doc/06-config.md#http-basic And it should be in the `.gitignore` file since it will have credentials in it.
2. While I understand the `*.json` may be too generous I can't see another way to accomplish making sure the `auth.json` is included when available/needed. If a WordPress project doesn't happen to need anything from our private Composer repository then the Docker build with fail if this file isn't available. And to be more specific the `f1 init` or `f1 new`, and I think Buildkite builds, will completely fail since the Docker image building will fail when this file is not available. This file needs to be a `.gitignore` file, and I think I may have missed adding that in to this PR for the initially generated file.

**Comment by timnolte** [comment]
@gustavderdrache I should have mentioned that in Buildkite builds the Composer authentication is already being taken care of via the AWS Secrets and an environment variable. I can't see how to accomplish this easily for local Docker container builds.

**Comment by gustavderdrache** [comment]
We had an offline discussion, and this PR is addressing a separate bug - there's an issue where the WordPress build target doesn't default to `dev` and thus attempts to perform an authenticated build. For local dev, we should only need to tweak the `.gitignore` to make sure people aren't committing their local `auth.json` files.

**Comment by timnolte** [comment]
@gustavderdrache I made the change and tested locally, however one show-stopper is the fact that it results in a prompting to overwirite the `.gitignore` file.
```
 conflict services/wordpress/.gitignore
? Overwrite services/wordpress/.gitignore? (ynaxdH)
```

**Comment by slucero** [comment]
I haven't run and tested this locally, but I believe the expectation would be that there would be a conflict in the `.gitignore` file that needs to be resolved right? We're changing the content that would be generated for it, so existing projects that run the generator to refresh the output would need to reconcile that change into their existing files.

Am I misunderstanding your last comment @timnolte?

**Comment by timnolte** [comment]
@slucero I tested on a new build setup and the web starter is getting stuck with a prompt to overwrite the .gitignore file for some reason. Seems like the way the .gitignore is being generated is causing a problem.

**Comment by slucero** [comment]
I've run a couple of tests of this branch locally.

### Existing installation

When running on an existing WordPress installation, the generator process completed without error. I was prompted for conflicts to both `.gitignore` and `.dockerignore` to which the new entries were both added successfully. After accepting the overwrite for each of these the process completed successfully.

### Fresh installation

When running a fresh install WP Starter ran a first time which produced the initial `.gitignore` file. It was then run a second time where it noted the `.gitignore` file already existed and would be preserved. Afterward, I was prompted with a conflict in the file which added the `auth.json` entry if I accepted it.

The `.dockerignore` file was also created and included the `auth.json` entry.

### Summary

In both cases, the update seemed to work without error. The workflow for a fresh installation wasn't ideal, but the final outcome was correct.

**Comment by timnolte** [comment]
@slucero 

> ### Summary
> In both cases, the update seemed to work without error. The workflow for a fresh installation wasn't ideal, but the final outcome was correct.

yeah, I think my concern is that prompt to overwrite the file on a fresh install. I'm not sure if there is some way around that. A solution wasn't jumping out at me.

**Comment by slucero** [comment]
@timnolte, I've spent most of this afternoon digging through and experimenting with the conflict resolution APIs in Yeoman, and I'm not seeing a good way to circumvent the prompt coming up without causing issues elsewhere.

In the interest of making the generator more immediately usable for WP installs I suggest we move forward with this as a known issue.

**Review by slucero — APPROVED** [review]

**Comment by slucero** [comment]
Merging this request resolves the missing `auth.json` entry for WP installs noted in #286

**Pull request merged**
